# Generated by Django 5.2.8 on 2025-11-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('emissions', models.FloatField(help_text='Emission value (e.g., tonnes CO2e)')),
                ('emission_type', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
    ]
